name: Purge GitHub container registry.

on:
  workflow_dispatch:
  # Runs daily at midnight
  schedule:
    - cron: '0 0 * * *'

jobs:
  purge-images:
    name: Delete old untagged images from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Delete all PR containers older than a week
        uses: snok/container-retention-policy@v2
        with:
          image-names: verapdf-rest:pr*, rest:pr*
          cut-off: 1 week ago UTC
          account-type: org
          org-name: veraPDF
          keep-at-least: 1
          untagged-only: false
          token: ${{ secrets.PAT }}
